### GET ALL USERS
GET http://127.0.0.1:3000/ HTTP/1.1

### GET ALL USERS ID
GET http://127.0.0.1:3000/8 HTTP/1.1

### POST A USER
POST http://127.0.0.1:3000/ HTTP/1.1
Content-Type: application/json

{
        "first_name": "Eraldo",
        "last_name": "Abedin",
        "email": "abedinieraldo@gmail.com"
}

### DELETE USER
DELETE http://127.0.0.1:3000/3 HTTP/1.1

### UPDATE USER
PUT http://127.0.0.1:3000/8 HTTP/1.1
Content-Type: application/json

{
        "first_name": "Michelle",
        "last_name": "Rossi",
        "email": "michellerossi@gmail.com"
}


